### PR TITLE
Update to es6

### LINKED ISSUE #9: Update to current shift specs
I've been doing a little work to update ```toShift``` and ```toSpidermonkey``` but before I get much further I'd like an idea of where this project is headed (if anywhere).

I started the update targeting Esprima but I could see targeting Babel or Acorn, maybe all of them.

I'd appreciate any feedback.

### PR DESCRIPTION
**Pull request by gabejohnson**
fixes #9

### CODE REVIEW

**Comment by michaelficarra** [comment]
Thanks, @gabejohnson. This is a great start. After a brief review, the only problem I've noticed is that it appears you're always generating `BindingIdentifier` nodes instead of generating `IdentifierExpression` nodes when a SpiderMonkey `Identifier` node is in expression position.

**Comment by gabejohnson** [comment]
@michaelficarra I was relying heavily on the tests in simple.js which are converting Spidermonkey->Shift->Spidermonkey.
I'm now going to add a pass through `shift-parser` and convert Shift->Spidermonkey->Shift as well.

**Comment by bakkot** [comment]
@gabejohnson, during development I'd strongly suggest importing from `"shift-ast/checked"` instead of `"shift-ast"`. This provides an identical interface, but the constructors will throw when given parameters of incorrect type. This will reveal a handful of bugs straight off.

**Comment by gabejohnson** [comment]
@bakkot, thanks for the tip. It's made a world of difference. Now I'm seeing a ton of type errors, but clearing them up is pretty straightforward.

**Comment by gabejohnson** [comment]
I just found some issues with Property and Identifier conversion. Will fix those and update.

**Comment by michaelficarra** [comment]
@gabejohnson Thanks. Please let us know when you've done so so that we know to do another review.

**Comment by gabejohnson** [comment]
@michaelficarra Ready for another review. Should I update the .travis.yml to target node v6 instead of v5?

**Comment by michaelficarra** [comment]
This is great. Thanks for the contribution, @gabejohnson! Merging.

**Comment by gabejohnson** [comment]
@michaelficarra, my pleasure! It was very educational.

**Pull request merged**
